### ISSUE TITLE
Link copy to slide down collection section forms is incorrect

### ISSUE THREAD

**Issue by raghubetina** [murugan-r/photogram_latest_fix_18#2]
<img width="799" alt="screen shot 2018-10-12 at 11 30 07 am" src="https://user-images.githubusercontent.com/811217/46881853-52e0d680-ce12-11e8-8837-94f669796e1d.png">

Links should say "Add like", "Add comment", etc.

**Comment by murugan-r** [comment]
Fixed in this commit https://github.com/firstdraft/ideas/commit/70b3f004091b88c20f2ab9c301c896d579d63d1c
