### ISSUE TITLE
Indirect collections should not have "Add x" link

### ISSUE THREAD

**Issue by raghubetina** [murugan-r/photogram_latest_fix_18#3]
<img width="766" alt="screen shot 2018-10-12 at 11 32 00 am" src="https://user-images.githubusercontent.com/811217/46881906-7dcb2a80-ce12-11e8-8413-3426dad811d8.png">

There are no forms to add to indirect collections, so there shouldn't be a link to slide the form down.

**Comment by murugan-r** [comment]
Fixed in this commit 
https://github.com/firstdraft/ideas/commit/70b3f004091b88c20f2ab9c301c896d579d63d1c
